folder_history:
- G:/GitHubProject/leica-watermark/tests/images
icons:
  apple: G:\GitHubProject\leica-watermark\src\asset\icons\apple.svg
  canon: G:\GitHubProject\leica-watermark\src\asset\icons\canon.svg
  fujifilm: G:\GitHubProject\leica-watermark\src\asset\icons\fujifilm.svg
  huawei: G:\GitHubProject\leica-watermark\src\asset\icons\huawei.svg
  leica: G:\GitHubProject\leica-watermark\src\asset\icons\leica.svg
  nikon: G:\GitHubProject\leica-watermark\src\asset\icons\nikon.svg
  olympus: G:\GitHubProject\leica-watermark\src\asset\icons\olympus.svg
  panasonic: G:\GitHubProject\leica-watermark\src\asset\icons\panasonic.svg
  sony: G:\GitHubProject\leica-watermark\src\asset\icons\sony.svg
  xiaomi: G:\GitHubProject\leica-watermark\src\asset\icons\xiaomi.svg
max_folder_history: 10
show_info:
  aperture: true
  camera: true
  camera_maker: true
  date: true
  focal_length: true
  gps: false
  iso: true
  lens: true
  shutter_speed: true
  time: true
watermark:
  bg_color:
  - 255
  - 255
  - 255
  - 255
  border:
    ratio: '4:3'
    size: 3%
  div_line_color:
  - 156
  - 156
  - 156
  - 255
  div_line_width: 10
  font:
    bold: G:\GitHubProject\leica-watermark\src\asset\fonts\SourceHanSansCN-Bold.otf
    light: G:\GitHubProject\leica-watermark\src\asset\fonts\SourceHanSansCN-Light.otf
  font_color:
  - 0
  - 0
  - 0
  - 255
  font_size: 20%
  margin: 3%
  text: LEICA
  text_area:
    height: 15%
    width: 100%
